services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80'   # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81'   # Admin Web Port   
    networks:
      - npm_public
volumes:
  npm_data:
    external: true

  npm_letsencrypt:
    external: true

networks:
  npm_public:
    driver: bridge
    name: npm_public


